services:
  backend:
    container_name: backend
    # image: fast
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    platform: linux/amd64 # (Patch for M1 Mac) Change Platform to linux/amd64 if you are on Linux
    build:
      context: ./backend
    env_file: 
      - ./backend/.env

  frontend:
    container_name: frontend
    # image: react
    ports:
      - 5173:5173   
    restart: always
    build:
      context: ./frontend

  db:
    container_name: database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DRIVER: pgsql

  proxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx_proxy_manager
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8090:81"
    environment:
        DB_SQLITE_FILE: "/data/db.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  data:
  letsencrypt:
